#include "uart_bms_protocol.h"

#include <assert.h>

const uart_bms_register_metadata_t g_uart_bms_registers[UART_BMS_REGISTER_COUNT] = {
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_01,
        .address = 0x0000,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 01",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:0)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_02,
        .address = 0x0001,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 02",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:1)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_03,
        .address = 0x0002,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 03",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:2)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_04,
        .address = 0x0003,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 04",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:3)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_05,
        .address = 0x0004,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 05",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:4)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_06,
        .address = 0x0005,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 06",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:5)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_07,
        .address = 0x0006,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 07",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:6)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_08,
        .address = 0x0007,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 08",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:7)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_09,
        .address = 0x0008,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 09",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:8)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_10,
        .address = 0x0009,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 10",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:9)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_11,
        .address = 0x000A,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 11",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:10)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_12,
        .address = 0x000B,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 12",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:11)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_13,
        .address = 0x000C,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 13",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:12)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_14,
        .address = 0x000D,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 14",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:13)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_15,
        .address = 0x000E,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 15",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:14)",
    },
    {
        .id = UART_BMS_REGISTER_CELL_VOLTAGE_16,
        .address = 0x000F,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_NONE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Cell Voltage 16",
        .unit = "mV",
        .comment = "Raw cell voltage (Reg:15)",
    },
    {
        .id = UART_BMS_REGISTER_LIFETIME_COUNTER,
        .address = 0x0020,
        .word_count = 2,
        .type = UART_BMS_VALUE_UINT32,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_UPTIME_SECONDS,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Tiny BMS lifetime counter",
        .unit = "s",
        .comment = "Read via UART/CAN (Reg:32)",
    },
    {
        .id = UART_BMS_REGISTER_ESTIMATED_TIME_LEFT,
        .address = 0x0022,
        .word_count = 2,
        .type = UART_BMS_VALUE_UINT32,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_ESTIMATED_TIME_LEFT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Estimated Time Left",
        .unit = "s",
        .comment = "Read via UART/CAN (Reg:34-35)",
    },
    {
        .id = UART_BMS_REGISTER_PACK_VOLTAGE,
        .address = 0x0024,
        .word_count = 2,
        .type = UART_BMS_VALUE_FLOAT32,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_PACK_VOLTAGE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Battery Pack Voltage",
        .unit = "V",
        .comment = "Read via UART/CAN (Reg:36)",
    },
    {
        .id = UART_BMS_REGISTER_PACK_CURRENT,
        .address = 0x0026,
        .word_count = 2,
        .type = UART_BMS_VALUE_FLOAT32,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_PACK_CURRENT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Battery Pack Current",
        .unit = "A",
        .comment = "Read via UART/CAN (Reg:38)",
    },
    {
        .id = UART_BMS_REGISTER_MIN_CELL_VOLTAGE,
        .address = 0x0028,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_MIN_CELL_MV,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Min Cell Voltage",
        .unit = "mV",
        .comment = "Read via UART/CAN (Reg:40)",
    },
    {
        .id = UART_BMS_REGISTER_MAX_CELL_VOLTAGE,
        .address = 0x0029,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_MAX_CELL_MV,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Max Cell Voltage",
        .unit = "mV",
        .comment = "Read via UART/CAN (Reg:41)",
    },
    {
        .id = UART_BMS_REGISTER_EXTERNAL_TEMPERATURE_1,
        .address = 0x002A,
        .word_count = 1,
        .type = UART_BMS_VALUE_INT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_AVERAGE_TEMPERATURE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "External Temperature #1",
        .unit = "\xB0C",
        .comment = "Read via UART/CAN (Reg:42)",
    },
    {
        .id = UART_BMS_REGISTER_EXTERNAL_TEMPERATURE_2,
        .address = 0x002B,
        .word_count = 1,
        .type = UART_BMS_VALUE_INT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_AUXILIARY_TEMPERATURE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "External Temperature #2",
        .unit = "\xB0C",
        .comment = "Read via UART/CAN (Reg:43)",
    },
    {
        .id = UART_BMS_REGISTER_STATE_OF_HEALTH,
        .address = 0x002D,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.002f,
        .primary_field = UART_BMS_FIELD_STATE_OF_HEALTH,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "State Of Health",
        .unit = "%",
        .comment = "Read via UART/CAN (Reg:45)",
    },
    {
        .id = UART_BMS_REGISTER_STATE_OF_CHARGE,
        .address = 0x002E,
        .word_count = 2,
        .type = UART_BMS_VALUE_UINT32,
        .scale = 0.000001f,
        .primary_field = UART_BMS_FIELD_STATE_OF_CHARGE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "State Of Charge",
        .unit = "%",
        .comment = "Read via UART/CAN (Reg:46)",
    },
    {
        .id = UART_BMS_REGISTER_INTERNAL_TEMPERATURE,
        .address = 0x0030,
        .word_count = 1,
        .type = UART_BMS_VALUE_INT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_MOS_TEMPERATURE,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Internal Temperature",
        .unit = "\xB0C",
        .comment = "Read via UART/CAN (Reg:48)",
    },
    {
        .id = UART_BMS_REGISTER_SYSTEM_STATUS,
        .address = 0x0032,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_SYSTEM_STATUS,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "System Status (online/offline)",
        .unit = "-",
        .comment = "Read via UART/CAN (Reg:50)",
    },
    {
        .id = UART_BMS_REGISTER_NEED_BALANCING,
        .address = 0x0033,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_NEED_BALANCING,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Need Balancing",
        .unit = "-",
        .comment = "Read via UART/CAN (Reg:51)",
    },
    {
        .id = UART_BMS_REGISTER_REAL_BALANCING_BITS,
        .address = 0x0034,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_BALANCING_BITS,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Real Balancing Bits",
        .unit = "-",
        .comment = "Read via UART/CAN (Reg:52)",
    },
    {
        .id = UART_BMS_REGISTER_MAX_DISCHARGE_CURRENT,
        .address = 0x0066,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_MAX_DISCHARGE_CURRENT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Max Discharge Current",
        .unit = "A",
        .comment = "Read via UART (Reg:102)",
    },
    {
        .id = UART_BMS_REGISTER_MAX_CHARGE_CURRENT,
        .address = 0x0067,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.1f,
        .primary_field = UART_BMS_FIELD_MAX_CHARGE_CURRENT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Max Charge Current",
        .unit = "A",
        .comment = "Read via UART (Reg:103)",
    },
    {
        .id = UART_BMS_REGISTER_PACK_TEMPERATURE_MIN_MAX,
        .address = 0x0071,
        .word_count = 1,
        .type = UART_BMS_VALUE_INT8_PAIR,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_PACK_TEMPERATURE_MIN,
        .secondary_field = UART_BMS_FIELD_PACK_TEMPERATURE_MAX,
        .name = "Pack Temperature Min",
        .unit = "\xB0C",
        .comment = "Read via UART/CAN (Reg:113, LSB = Min, MSB = Max)",
    },
    {
        .id = UART_BMS_REGISTER_PEAK_DISCHARGE_CURRENT_CUTOFF,
        .address = 0x0131,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_PEAK_DISCHARGE_CURRENT_LIMIT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Peak Discharge Current Cutoff",
        .unit = "A",
        .comment = "Read via CAN (Reg:305)",
    },
    {
        .id = UART_BMS_REGISTER_BATTERY_CAPACITY,
        .address = 0x0132,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 0.01f,
        .primary_field = UART_BMS_FIELD_BATTERY_CAPACITY,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Battery Capacity",
        .unit = "Ah",
        .comment = "Read via UART/CAN (Reg:306)",
    },
    {
        .id = UART_BMS_REGISTER_SERIES_CELL_COUNT,
        .address = 0x0133,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_SERIES_CELL_COUNT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Number Of Series Cells",
        .unit = "cell",
        .comment = "Read via CAN (Reg:307)",
    },
    {
        .id = UART_BMS_REGISTER_OVERVOLTAGE_CUTOFF,
        .address = 0x013B,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_OVERVOLTAGE_CUTOFF,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Overvoltage Cutoff",
        .unit = "mV",
        .comment = "Read via UART/CAN (Reg:315)",
    },
    {
        .id = UART_BMS_REGISTER_UNDERVOLTAGE_CUTOFF,
        .address = 0x013C,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_UNDERVOLTAGE_CUTOFF,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Undervoltage Cutoff",
        .unit = "mV",
        .comment = "Read via UART/CAN (Reg:316)",
    },
    {
        .id = UART_BMS_REGISTER_DISCHARGE_OVER_CURRENT_CUTOFF,
        .address = 0x013D,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_DISCHARGE_OVER_CURRENT_LIMIT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Discharge Over-current Cutoff",
        .unit = "A",
        .comment = "Read via UART/CAN (Reg:317)",
    },
    {
        .id = UART_BMS_REGISTER_CHARGE_OVER_CURRENT_CUTOFF,
        .address = 0x013E,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_CHARGE_OVER_CURRENT_LIMIT,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Charge Over-current Cutoff",
        .unit = "A",
        .comment = "Read via UART/CAN (Reg:318)",
    },
    {
        .id = UART_BMS_REGISTER_OVERHEAT_CUTOFF,
        .address = 0x013F,
        .word_count = 1,
        .type = UART_BMS_VALUE_INT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_OVERHEAT_CUTOFF,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Overheat Cutoff",
        .unit = "\xB0C",
        .comment = "Read via UART/CAN (Reg:319)",
    },
    {
        .id = UART_BMS_REGISTER_LOW_TEMP_CHARGE_CUTOFF,
        .address = 0x0140,
        .word_count = 1,
        .type = UART_BMS_VALUE_INT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_LOW_TEMP_CHARGE_CUTOFF,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Low Temp Charge Cutoff",
        .unit = "\xB0C",
        .comment = "Read via UART/CAN (Reg:320)",
    },
    {
        .id = UART_BMS_REGISTER_HARDWARE_VERSION,
        .address = 0x01F4,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_HARDWARE_VERSION,
        .secondary_field = UART_BMS_FIELD_HARDWARE_CHANGES_VERSION,
        .name = "Hardware/Changes Version",
        .unit = "-",
        .comment = "Reg:500. HW Ver (LSB), HW Changes Ver (MSB)",
    },
    {
        .id = UART_BMS_REGISTER_PUBLIC_FIRMWARE_FLAGS,
        .address = 0x01F5,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_FIRMWARE_VERSION,
        .secondary_field = UART_BMS_FIELD_FIRMWARE_FLAGS,
        .name = "Public Firmware/Flags",
        .unit = "-",
        .comment = "Reg:501. Public FW Ver (LSB), Flags (MSB)",
    },
    {
        .id = UART_BMS_REGISTER_INTERNAL_FIRMWARE_VERSION,
        .address = 0x01F6,
        .word_count = 1,
        .type = UART_BMS_VALUE_UINT16,
        .scale = 1.0f,
        .primary_field = UART_BMS_FIELD_INTERNAL_FIRMWARE_VERSION,
        .secondary_field = UART_BMS_FIELD_NONE,
        .name = "Internal Firmware Version",
        .unit = "-",
        .comment = "Reg:502",
    },
};

const size_t g_uart_bms_register_count = UART_BMS_REGISTER_COUNT;

const uint16_t g_uart_bms_poll_addresses[UART_BMS_REGISTER_WORD_COUNT] = {
    0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008,
    0x0009, 0x000A, 0x000B, 0x000C, 0x000D, 0x000E, 0x000F, 0x0020, 0x0021,
    0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027, 0x0028, 0x0029, 0x002A,
    0x002B, 0x002D, 0x002E, 0x002F, 0x0030, 0x0032, 0x0033, 0x0034, 0x0066,
    0x0067, 0x0071, 0x0131, 0x0132, 0x0133, 0x013B, 0x013C, 0x013D, 0x013E,
    0x013F, 0x0140, 0x01F4, 0x01F5, 0x01F6, 0x01F7, 0x01F8, 0x01F9, 0x01FA,
    0x01FB, 0x01FC, 0x01FD, 0x01FE, 0x01FF,
};

const uart_bms_register_metadata_t *uart_bms_protocol_find_by_address(uint16_t address)
{
    for (size_t i = 0; i < UART_BMS_REGISTER_COUNT; ++i) {
        const uart_bms_register_metadata_t *meta = &g_uart_bms_registers[i];
        for (uint8_t w = 0; w < meta->word_count; ++w) {
            if ((uint16_t)(meta->address + w) == address) {
                return meta;
            }
        }
    }
    return NULL;
}

static_assert((sizeof(g_uart_bms_poll_addresses) / sizeof(g_uart_bms_poll_addresses[0])) ==
                  UART_BMS_REGISTER_WORD_COUNT,
              "Poll address table size must match register word count");

